### ISSUE TITLE
rdfstore-js 

### ISSUE THREAD

**Issue by danbri** [agrueneberg/Sparqling#8]
Did the license change? https://github.com/antoniogarrote/rdfstore-js/blob/master/LICENSE seems to be MIT now. Does MIT apply to the version you use here?

**Comment by agrueneberg** [comment]
Hi Dan,

you're right, it looks like the license changed in 2013. The fork of rdfstore-js this project is (or rather was) based on is from 2012 and does not contain a LICENSE file, but a note at the bottom of the README: https://github.com/agrueneberg/rdfstore-js Glad to see @antoniogarrote is still working on it!

Cheers,
Alex
